### ISSUE TITLE
problem connecting to rdp server

### ISSUE THREAD

**Issue by neermine** [jimmy201602/webterminal#103]
Hello i need same help please i could not connect to rdp server and this error keep showing up. What can i do ? and thanks
![image](https://user-images.githubusercontent.com/49228719/55464585-58fe8580-55f3-11e9-973e-91c82513b10f.png)

**Comment by jimmy201602** [comment]
Obviously, you should check your server can connect to the target server.

**Comment by neermine** [comment]
Hi ! my server can connect to the target server as you can see:
![image](https://user-images.githubusercontent.com/49228719/55706638-955a2900-59d9-11e9-8a8d-8537f7c26e1d.png)

**Comment by neermine** [comment]
Hiiii i did find the problem in fact i forgot to tape the command **/etc/init.d/guacd start** . Thanks
