### ISSUE TITLE
Change timezone of log list

### ISSUE THREAD

**Issue by vhostvn** [jimmy201602/webterminal#106]
Hi Jimmy,

May i know how to change timezone of **log list**?

timezone of container is correct already but timezone under this page is still UTC +0
![2019-05-03_19-42-44](https://user-images.githubusercontent.com/16444776/57138038-d0365d80-6ddb-11e9-9590-45e6a863392c.png)

**Comment by jimmy201602** [comment]
This is a bug.By default if you choose English . The the timezone use utc +0 time. This will fixed in the next release. Please wait for some days.

**Comment by vhostvn** [comment]
I tried to change line 125 from this file: webterminal/settings.py

The default setting was UTC and i change to GMT+7 with no luck.

I tried another setting: Asia/Ho_Chi_Minh and no luck too, is there anyway to get over this?

![2019-05-03_21-05-31](https://user-images.githubusercontent.com/16444776/57142647-4b514100-6de7-11e9-850a-546951656319.png)

**Comment by jimmy201602** [comment]
Just change all the in 
```sh 
<td>{% ifequal LANGUAGE_CODE 'zh-hans' %}{{ element.start_time|timezone:"Asia/Shanghai" }}{%else%}{{element.start_time}}{%endifequal%}</td>
```
in https://github.com/jimmy201602/webterminal/blob/master/common/templates/common/logslist.html

**Comment by vhostvn** [comment]
do we have to stop and start docker again? do we have to modify this file webterminal/settings.py and rebuild again?

Thanks,

**Comment by vhostvn** [comment]
we change them as your suggestion:

`[root@gw webterminal]# grep timezone common/templates/common/logslist.html
                            <td>{% ifequal LANGUAGE_CODE 'zh-hans' %}{{ element.start_time|timezone:"Asia/Ho_Chi_Minh" }}{%else%}{{element.start_time}}{%endifequal%}</td>
                                    <a class="btn btn-xs btn-primary play" onclick="play('{{element.user.username}}','{{element.server.ip}}','{% ifequal LANGUAGE_CODE 'zh-hans' %}{{element.start_time|timezone:"Asia/Ho_Chi_Minh"}}{%else%}{{element.start_time|localtime}}{%endifequal%}','{% ifequal LANGUAGE_CODE 'zh-hans' %}{{element.end_time|timezone:"Asia/Ho_Chi_Minh"}}{%else%}{{element.end_time|localtime}}{%endifequal%}',{% if element.server.credential.protocol == 'ssh-password' or element.server.credential.protocol == 'ssh-key' %} '{% url 'sshlogplay' element.id %}' {% else %} '{% url 'guacamolelogplay' element.id %}' {% endif %} );">{%trans 'replay' %}</a>
                                {% if element.server.credential.protocol == 'ssh-password' or element.server.credential.protocol == 'ssh-key' %}<a class="btn btn-xs btn-success" onclick="monitor('{{element.user.username}}','{{element.server.ip}}','{% ifequal LANGUAGE_CODE 'zh-hans' %}{{element.start_time|timezone:"Asia/Ho_Chi_Minh"}}{%else%}{{element.start_time|localtime}}{%endifequal%}','{% url 'sshterminalmonitor' element.id %}',)">{% else %}<a class="btn btn-xs btn-success" onclick="monitorguacamole('{{element.user.username}}','{{element.server.ip}}','{% ifequal LANGUAGE_CODE 'zh-hans' %}{{element.start_time|timezone:"Asia/Ho_Chi_Minh"}}{%else%}{{element.start_time|localtime}}{%endifequal%}','{% url 'guacamolemonitor' element.id %}',)">{% endif %}{%trans 'monitor' %}</a>
[root@gw webterminal]#
`

then run below command but they did not change:

```
docker container stop ec51202f0940
docker build -t root/gw .
docker container start ec51202f0940
```

**Comment by jimmy201602** [comment]
Modify to this. try again.
{% ifequal LANGUAGE_CODE 'zh-hans' %}{{element.start_time|timezone:"Asia/Ho_Chi_Minh"}}{%else%}{{element.start_time|timezone:"Asia/Ho_Chi_Minh"}}{%endifequal%}'

**Comment by vhostvn** [comment]
which line i have to change because i see many lines has the same keyword by search

![2019-05-04_21-10-04](https://user-images.githubusercontent.com/16444776/57180267-0a256380-6eb1-11e9-8a03-8890feb9cf6a.png)
