### ISSUE TITLE
Do not see TOTP

### ISSUE THREAD

**Issue by vhostvn** [jimmy201602/webterminal#107]
Hi,

I see this guide: https://github.com/jimmy201602/webterminal/blob/master/doc/usage_en.md#add-2f-authentification-to-users mentioned TOTP but after deploy and going to admin, i can not see them there.

![2019-05-03_21-11-10](https://user-images.githubusercontent.com/16444776/57142972-024dbc80-6de8-11e9-9063-84c4abcdadc4.png)

**Comment by jimmy201602** [comment]
These code currently not used in this project. It will be use in the future.
