### ISSUE TITLE
前台putty关闭后，后台到服务器的连接没有中断

### ISSUE THREAD

**Issue by maxtorgithub** [jimmy201602/webterminal#109]
使用docker最新版安装后，我主要测试对网络设备的兼容情况，测试后发现，有后台连接不中断的情况，造成设备登录几次后，连接数占满无法继续登录。具体有如下情况，
1、到某些型号的网络设备(Juniper防火墙）关闭putty或者输入exit退出后，后台连接均未中断。
通过命令exit断开putty的日志
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:EOF in transport thread
直接关闭putty的日志
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:EOF in transport thread

2、某些型号的设备（某些华为交换机）
通过exit退出putty，后台日志，这种情况下，后台连接立刻中断
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 32768 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:Ignoring message for dead channel 0
INFO:paramiko.transport:Disconnect (code 2): The connection is closed by SSH server
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:EOF in transport thread

直接关闭putty的日志与juniper防火墙日志一致，但华为交换机直接关闭后大概15分钟后，后台连接中断，出现了日志
INFO:paramiko.transport:Disconnect (code 2): The connection is closed by SSH server
juniper防火墙永不终端

**Comment by jimmy201602** [comment]
暂时没有精力支持路由器交换机非标ssh协议,如可远程可以联调一下!

**Comment by jimmy201602** [comment]
bug已修复

**Comment by maxtorgithub** [comment]
测试了一下 ，现象和之前一样

**Comment by jimmy201602** [comment]
重试下!
