### ISSUE TITLE
在web terminal shell上打exit会有问题

### ISSUE THREAD

**Issue by BeerLii** [jimmy201602/webterminal#11]
if x == "exit\r\n" or x == "logout\r\n" or x == 'logout':
                    chan.close()
                else:
                    if isinstance(x,unicode):
                        stdout.append([delay,x])
                    else:
                        stdout.append([delay,codecs.getincrementaldecoder('UTF-8')('replace').decode(x)])

这一段上x是bytes类型的 比较我觉得要转成str先 
stdout.append([delay,codecs.getincrementaldecoder('UTF-8')('replace').decode(x)])
这段应该要在if x == "exit\r\n" or x == "logout\r\n" or x == 'logout':
                    chan.close() 
这里的close上放一个

**Comment by jimmy201602** [comment]
This is not a bug!
