### ISSUE TITLE
使用双因子验证的服务器登录有问题 

### ISSUE THREAD

**Issue by grin3** [jimmy201602/webterminal#110]
`Can not connect to server: ('Bad authentication type', [u'gssapi-keyex', u'gssapi-with-mic', u'keyboard-interactive']) (allowed_types=[u'gssapi-keyex', u'gssapi-with-mic', u'keyboard-interactive'])`

服务器配置了ssh登录需要双因子验证。使用keyboard-interactive方式登录。现在不支持。
keyboard-interactive需输入两次密码。

**Comment by jimmy201602** [comment]
暂时不支持双因子登录
