### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by xmlgrg** [jimmy201602/webterminal#112]
希望可以允许 个人账号可以 修改自身的登录密码

**Comment by jimmy201602** [comment]
后续新增一个密码重置功能

**Comment by jimmy201602** [comment]
已新增密码重置功能,使用方法如下:
1:登录界面点击Forget Pasword按钮,跳转重置密码界面,
2:输入需要重置密码的账户email地址
3:在收到邮件后自助重置密码

前置条件,项目新增发送邮箱设置,使用方法如下:
1:cp extra_settings.py.example extra_settings.py
2:这里以gmail为例,请参照以下文章进行设置(https://data-flair.training/blogs/django-send-email/)
