### ISSUE TITLE
登录超时的问题

### ISSUE THREAD

**Issue by xmlgrg** [jimmy201602/webterminal#113]
登录后超过十分钟没有操作，就需要重新登录

**Comment by jimmy201602** [comment]
https://stackoverflow.com/questions/14830669/how-to-expire-django-session-in-5minutes
可以参考并设置下

**Comment by jimmy201602** [comment]
暂时设置为关闭浏览器需要重新登录!另外会话超时时间设置为三十分钟!后续添加一个十分钟没有操作就需重登陆的功能

**Comment by jimmy201602** [comment]
项目新增一个设置超时时间配置选项,模板为extra_settings.py.example,使用方法如下:
1:cp extra_settings.py.example extra_settings.py
2:修改SESSION_COOKIE_AGE项为合适的时间,单位为秒,重启站点即可生效
