### ISSUE TITLE
after loging in stystem, browser make redirect with error

### ISSUE THREAD

**Issue by connected201** [jimmy201602/webterminal#114]
hi, i installed docker, and after logging, in system, browser make redirect, with error like The address wasn’t understood 
URL you can see in screen:
![OFxQ95WsKn](https://user-images.githubusercontent.com/20506433/61645542-80b34f80-acaf-11e9-8609-6dcf09be8360.png)
what i need to install, on my PC (Windows 10) to fix it? as i understand i need to have some associated app on my PC to open this link?

**Comment by jimmy201602** [comment]
Try to use chrome instead. Currently i haven't test on firefox.

**Comment by connected201** [comment]
i fixed it, need to install webterminal ssh helper, in Firefox don't appear banner to download, in opera appear
