### ISSUE TITLE
OTP

### ISSUE THREAD

**Issue by jorgeaaq70** [jimmy201602/webterminal#115]
I am trying to enable OTP but i get an error

OperationalError: no such table: otp_totp_totpdevice

how can I create that table? 

work with sqlite or i need to change to mysql (mariadb)

I am working with Centos 7 and after some changes on installation process, I make it work , but I want offer to my users OTP but I cannot make it work 

can you help me

thanks in Advance

Jorge A Arenas

**Comment by jimmy201602** [comment]
Please wait for several week!

**Comment by jimmy201602** [comment]
I will add otp in the future!

**Comment by jimmy201602** [comment]
I have already make otp function work,Just wait for several days! I need do some other extra work to make it easily use. I'm sorry, I am so slow at this.

**Comment by jimmy201602** [comment]
This function has been added!
