### ISSUE TITLE
分组下创建超过10个主机,出现主机错位情况？

### ISSUE THREAD

**Issue by LookingDreamer** [jimmy201602/webterminal#116]
问题描述:
当创建超过10个主机，第11个主机会自动连接到第1个主机

比如我要连接10.68.3.84，但是实际上连接到10.68.3.60这台主机了
![image](https://user-images.githubusercontent.com/11344104/64006909-ccc2a100-cb45-11e9-88f2-c813150f9470.png)

![image](https://user-images.githubusercontent.com/11344104/64006929-d3511880-cb45-11e9-9853-8e18369f0b16.png)

**Comment by jimmy201602** [comment]
#116 fixed
