### ISSUE TITLE
升级 python3

### ISSUE THREAD

**Issue by LB-J** [jimmy201602/webterminal#118]
是否有考虑过升级python3，目前 django 的channels 已经到了2.x版本，channels redis 的已经不支持以前的用法了

**Comment by jimmy201602** [comment]
现在项目已经是python3运行环境了！django版本未来会升级到2版本，channels也将会更新，如果有兴趣可以一块参与进来！
目前精力时间有限，项目涉及到代码太多，为保证项目稳定性，暂无精力进行测试及更新

**Comment by liu839611980** [comment]
对于运维工作者，是一款很好的选择

**Comment by LB-J** [comment]
原来如此，我升级到了django 2.x channels 也升级了。目前 channels_layers。

**Comment by LB-J** [comment]
确实不错，channels 升级之后不再支持 redis pub 。而且 websocket  receive 只能有一个监听，我现在把send到页面的方法直接放在了 receive 里，不再单独拎出来放在线程里了

**Comment by jimmy201602** [comment]
为什么不把你更改的代码推个pr呢?

**Comment by LB-J** [comment]
抱歉，我这边只是用到了 channels 用来实现 docker container 的 web console。如果需要的话，我可以提供我修改后的，websocket 连接这部分代码。

**Comment by jimmy201602** [comment]
come on boys!
