### ISSUE TITLE
webterminal WEB(webrdp）情况下的可能错误:

### ISSUE THREAD

**Issue by 841733986** [jimmy201602/webterminal#129]
1：无法上传 "新建.txt".(不支持中文名）
'ascii' codec can't encode characters in position 36-37: ordinal not in range(128)
2：发现几次未能成功映射G盘（Guacamole RDP） 未做长久测试
3：成功映射G盘（Guacamole RDP）后，WEB端会提示:无效的后端响应.Error occurred on the server side.   HTTP error 500

**Comment by jimmy201602** [comment]
1：无法上传 "新建.txt".(不支持中文名）
'ascii' codec can't encode characters in position 36-37: ordinal not in range(128)  
暂未在windows下做测试,后续测试
2：发现几次未能成功映射G盘（Guacamole RDP） 
未做长久测试 目前请使用编译好的docker镜像安装
3：成功映射G盘（Guacamole RDP）后，WEB端会提示:无效的后端响应.Error occurred on the server side. HTTP error 500
本地测试未发现此bug,后续你可联系我远程重现此bug

**Comment by jimmy201602** [comment]
1：无法上传 "新建.txt".(不支持中文名）
已经修复
2：发现几次未能成功映射G盘（Guacamole RDP）
未做长久测试 目前请使用编译好的docker镜像安装
3：成功映射G盘（Guacamole RDP）后，WEB端会提示:无效的后端响应.Error occurred on the server side. HTTP error 500
参考#131
