### ISSUE TITLE
webterminal功能建议

### ISSUE THREAD

**Issue by 841733986** [jimmy201602/webterminal#130]
日志列表建议
 1:WEBRDP时 监控功能失效
2:建议显示录像的文件大小 方便确认是要看的录像
3:因为使用的DOCKER来装的webterminal 手动进去复制录像有点困难，建议增加一个下载录像的功能
其他功能建议
1:增加HTTPS支持
2:增减SMTP邮件服务并支持密码找回功能
3:增加广告栏 建议WEB滚动形式 （管理员可发布） 或者内置网页版本群聊 推荐一个群聊的：https://github.com/yinxin630/fiora

**Comment by jimmy201602** [comment]
1:WEBRDP时 监控功能失效
这个是guacd bug,待修复
2:建议显示录像的文件大小 方便确认是要看的录像 录像大小暂无必要显示,若有,后续添加
3:因为使用的DOCKER来装的webterminal 手动进去复制录像有点困难，建议增加一个下载录像的功能 docker可以映射主机上的文件夹至docker内部,后续优化
其他功能建议
1:增加HTTPS支持 https功能是你nginx反代理的功能,你可尝试配置一个带https的反代理
2:增减SMTP邮件服务并支持密码找回功能 待优化功能
3:增加广告栏 建议WEB滚动形式 （管理员可发布） 或者内置网页版本群聊 推荐一个群聊的：https://github.com/yinxin630/fiora 暂时和项目主旨冲突,近期没有打算新增此功能

**Comment by jimmy201602** [comment]
2:增减SMTP邮件服务并支持密码找回功能 此功能已经新增,请查看 #112

**Comment by jimmy201602** [comment]
1:WEBRDP时 监控功能失效
最新版本已修复,静待最新版本的发布

**Comment by jimmy201602** [comment]
Try to use docker tag beta (webterminal/webterminal:beta)
