### ISSUE TITLE
真心觉得这个项目非常之好，我想当主运维系统用 有三个问题看能不能最近优先解决一下呢

### ISSUE THREAD

**Issue by 841733986** [jimmy201602/webterminal#131]
1:增加一下 用户第一次登录时修改密码
2:屏蔽需要装插件的提醒
3:window服务器远程时文件上传与下载的时候 中文文件名报错的问题

另外之前反馈的未成功映射G盘的问题 应该是之前的连接未断开导致 因为是单机测试 误以为是BUG

**Comment by jimmy201602** [comment]
1:增加一下 用户第一次登录时修改密码
优化建议采纳
3:window服务器远程时文件上传与下载的时候 中文文件名报错的问题
编码问题,已修复部分
3:window服务器远程时文件上传与下载的时候 中文文件名报错的问题
另外之前反馈的未成功映射G盘的问题 应该是之前的连接未断开导致 因为是单机测试 误以为是BUG
感谢反馈

**Comment by jimmy201602** [comment]
3:window服务器远程时文件上传与下载的时候 中文文件名报错的问题
已修复,经测试未发现异常,请测试后告知结果

**Comment by jimmy201602** [comment]
2:屏蔽需要装插件的提醒
已经添加控制参数,后续测试后将放出

**Comment by jimmy201602** [comment]
2:屏蔽需要装插件的提醒
已经添加控制参数,已经添加配置界面

**Comment by jimmy201602** [comment]
1:增加一下 用户第一次登录时修改密码
此功能已经由忘记密码重置功能替代!
