### ISSUE TITLE
webterminal ssh helper

### ISSUE THREAD

**Issue by mstools** [jimmy201602/webterminal#133]
webterminal ssh helper 能不能加一个centos的包,,
我想把项目搭建在centos下面..

**Comment by jimmy201602** [comment]
正在写新版本的调用助手，暂等一段时间

**Comment by mstools** [comment]
再请教个问题,,
为什么我在webterminal.urls找不到/ws/路径匹配,,?

**Comment by jimmy201602** [comment]
请参考django channels，这个是websocket协议，目前用的channels 1版本

**Comment by mstools** [comment]
谢谢指导..

**Comment by jimmy201602** [comment]
已经新增了Linux版本的调用助手,centos目前还没有打rpm包,后续会加入包,你可先使用以下安装包自定义安装!https://github.com/jimmy201602/webterminal/blob/master/helper/Webterminal%20Helper.tar.bz2
解压文件包分别至对应的系统目录下,然后以root账户执行/opt/Webterminal\ Helper/registerurlscheme.sh 注册wssh调用助手协议即可在Linux下使用助手去连接指定的服务器
历时八月写的调用助手,有可能有bug,感谢使用测试
