### ISSUE TITLE
打开文件管理器打开失败

### ISSUE THREAD

**Issue by chenxianxu** [jimmy201602/webterminal#135]
新拉起的docker应用打开文件管理器打开不了

**Comment by chenxianxu** [comment]
文件上传

**Comment by jimmy201602** [comment]
待修复！

**Comment by jimmy201602** [comment]
经浮现为docker镜像中language_code问题,具体可自行百度,后续新增docker优化选项

**Comment by jimmy201602** [comment]
这种问题浮现,为上传的文件编码问题,已加处理,待后续发布新的版本可解决此问题

**Comment by jimmy201602** [comment]
Try to use docker tag beta (webterminal/webterminal:beta)
