### ISSUE TITLE
某些http接口对于有反向代理的服务来说支持不好

### ISSUE THREAD

**Issue by wuchunhuan** [jimmy201602/webterminal#140]
比如：
docker容器运行，端口假设，宿主：38001，docker应用：80
服务器域名: www.example.com
服务器nginx反向代理端口:38000

请求路径：
外网      ->       nginx反向代理(38001)           ->         webterminal_docker(38000:80)

请求如下：
```
https://www.example.com:38000/common/api/serverinfo/1/
```
得到如下相应（application/json）：
```
url: "http://www.example.com/common/api/serverinfo/1/", updatedatetime: "2020-04-21T07:08:18.933392Z",…}
url: "http://www.example.com/common/api/serverinfo/1/"
updatedatetime: "2020-04-21T07:08:18.933392Z"
name: "xxx"
hostname: "xxx"
ip: "192.168.1.111"
createdatetime: "2020-04-21T07:08:18.933519Z"
credential: "http://www.example.com/common/api/credential/1/"
```

然后浏览器紧接着请求：http://www.example.com/common/api/credential/1/，必然会失败（先忽略https的问题）

以上结果，docker认为服务的端口是80，所以响应结果里边没有设置端口号（默认80），但是docker应用不应该做这种宿主机和反向代理也用一样端口的假设吧，是不是应该把响应结果里边的url中端口设置为host中的端口呢（`credential: "http://www.example.com:38000/common/api/credential/1/"`）？
这样nginx作为反代，可以在host中增加端口号，应该就没问题了。

**Comment by wuchunhuan** [comment]
还有一个问题：
![image](https://user-images.githubusercontent.com/7456445/79853663-e8dbc100-83fa-11ea-99f7-4f52663d7e10.png)
![image](https://user-images.githubusercontent.com/7456445/79853756-0ad54380-83fb-11ea-9ea8-bb366cacfbeb.png)
可以考虑放到本地。。。

**Comment by jimmy201602** [comment]
反向代理的问题是你对docker使用问题，启动时可以自定义映射端口，并未做限制！本身docker启动时已经用了nginx做了一层反向代理。。。多层反向代理的情况暂时未用到。。。所以暂未测试。。。
代码里有做用户数使用情况统计，类似百度的统计！只统计了有多少用户数使用这个系统！

**Comment by wuchunhuan** [comment]
不是自定义端口映射的问题，而是返回的结果里边，默认是80端口的，宿主机做的端口映射38001，但是浏览器收到的结果仍然是不带端口的（默认80），我的意思是能支持从请求的host中获取真实的端口最好，不管有几层proxy。

**Comment by pandaxin** [comment]
https://mattrobenolt.com/handle-x-forwarded-port-header-in-django/
![image](https://user-images.githubusercontent.com/13793251/80119391-3a7f7980-85bc-11ea-8244-4912c6fcc754.png)

**Comment by jimmy201602** [comment]
非常感谢这位老哥的解释，晚点我将代码上加上这块

**Comment by jimmy201602** [comment]
https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-USE_X_FORWARDED_PORT
# django settings里面加上如下参数即可
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
