### ISSUE TITLE
Is it possible to export/import the system config?

### ISSUE THREAD

**Issue by cunningr** [jimmy201602/webterminal#146]
We would like to store the system config as code and deploy via docker.  Is it possible to build/modify credentials/users/servers/groups and import or install at run time?

**Comment by jimmy201602** [comment]
That's easy! For now, all related data was save in db.sqlite file and all recording save in the media directory. Just backup these files.

**Comment by maxicoffee** [comment]
Hello is this possible to move db.sqlite3 in a subdirectory, so we can volumify this subdirectory in docker ?

Thanks !

**Comment by jimmy201602** [comment]
try to use the beta version.
