### ISSUE TITLE
客户端助手安装后报错

### ISSUE THREAD

**Issue by ducc01** [jimmy201602/webterminal#155]
![图片](https://user-images.githubusercontent.com/50479652/103127812-f8b84d00-46cd-11eb-8794-3dcc090676b1.png)

**Comment by jimmy201602** [comment]
待解决bug

**Comment by bigcaibao** [comment]
WIN10用户吧,我仔细检查了下,助手对权限要求好像有点问题,你尝试安装在D盘,不要安装在C盘默认目录,右键属性勾选使用管理员权限运行.

**Comment by jimmy201602** [comment]
新版已经发布,帮忙测试下

**Comment by bigcaibao** [comment]
@jimmy201602 晚点我在虚拟机上看看.
