### ISSUE TITLE
ssh helper无法安装

### ISSUE THREAD

**Issue by Bo520** [jimmy201602/webterminal#158]
我是Windows10专业版1909，下载helper之后点击一直转圈无法打开，然后资源管理器会卡死。
![image](https://user-images.githubusercontent.com/53036043/106599100-8facda80-6593-11eb-95f2-013e9659da44.png)

**Comment by jimmy201602** [comment]
待解决bug

**Comment by jimmy201602** [comment]
新版发布,请帮忙测试
