### ISSUE TITLE
rdp issue

### ISSUE THREAD

**Issue by perfectwebtech** [jimmy201602/webterminal#159]
rdp does not work on web base

is it additional dependency need to install ? 

as well ie icon seems only shold work ie browser ?

**Comment by jimmy201602** [comment]
I recommend you use chrome.

**Comment by perfectwebtech** [comment]
ok fixed now one more thing big issue

if i connect 50 servers then i try to execution one time then only some server ocnnect rest of got issue 

red color:  Can not connect to server: No existing session

if single connect then works fine any idea or settings something would be helpfull plz
