### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by perfectwebtech** [jimmy201602/webterminal#160]
if i connect 50 servers then i try to execution one time then only some server ocnnect rest of got issue

red color: Can not connect to server: No existing session

if single connect then works fine any idea or settings something would be helpfull plz

**Comment by jimmy201602** [comment]
Need to be tested.

**Comment by perfectwebtech** [comment]
can fix as possible ?  i can do donation too

**Comment by jimmy201602** [comment]
You can send me an email to communicate with the detail.

**Comment by perfectwebtech** [comment]
parbatwebmaster@gmail.com

**Comment by jimmy201602** [comment]
zhengge2012@gmail.com

**Comment by jimmy201602** [comment]
Try to use docker tag beta (webterminal/webterminal:beta)
