### ISSUE TITLE
remember password

### ISSUE THREAD

**Issue by perfectwebtech** [jimmy201602/webterminal#161]
hello

is there way eanble remember password for login ? username and password it will be offten session logout so 

or where is session time i can setup ?

**Comment by jimmy201602** [comment]
Enhancement function

**Comment by perfectwebtech** [comment]
if u done for me  web terminal there checkbox too multi connect and if i click on tab then again new tab open like this funtion u can done qjickly ? i will pay donation

**Comment by jimmy201602** [comment]
You mean to duplicate the session?

**Comment by jimmy201602** [comment]
> hello
> 
> is there way eanble remember password for login ? username and password it will be offten session logout so
> 
> or where is session time i can setup ?

You can modify the session manually. For now, it's default 30 minutes for security reasons. You can modify the file webterminal/settings.py.
# session will expire in 30 minutes
SESSION_COOKIE_AGE = 30 * 60

**Comment by perfectwebtech** [comment]
ok where i can get your email ?

**Comment by jimmy201602** [comment]
zhengge2012@gmail.com

**Comment by jimmy201602** [comment]
The function has been added in the beta version.
Try to use docker tag beta (webterminal/webterminal:beta)
