### ISSUE TITLE
Change/removing your head in profile picture

### ISSUE THREAD

**Issue by spasquet33** [jimmy201602/webterminal#163]
Hello, can we remove the top right fake notification ? Can we change the profile picture ?
I try to create a new user but we always have the same profile picture and the same fake notifications.

Thanks a lot !

**Comment by jimmy201602** [comment]
Try to use docker tag beta (webterminal/webterminal:beta)
due to https://github.com/FreeRDP/FreeRDP/issues/
you can not use rdp/vnc/telnet protocol

**Comment by jimmy201602** [comment]
Try to use docker tag beta (webterminal/webterminal:beta)
