### ISSUE TITLE
服务器列表存在相同IP的数据，则客户端打不开

### ISSUE THREAD

**Issue by zjun123123** [jimmy201602/webterminal#164]
如题，管理员在服务器列表菜单 ，添加服务器时，如果存在IP都是相同的数据时，那么相应分配了此服务器权限的用户，打开的此服务器的客户端时，一直卡在那，一直显示的是黑屏，请问这是不是有问题啊?

**Comment by jimmy201602** [comment]
请提供更多信息,根据你的描述无法定位问题.

**Comment by jimmy201602** [comment]
Try to use docker tag beta (webterminal/webterminal:beta)
