### ISSUE TITLE
RE: Turn off the machien and everything is lost on startup so a proper install document is needed

### ISSUE THREAD

**Issue by Fuquan999** [jimmy201602/webterminal#176]
Hi Jimmy,
I came across this recently and decided to try it out as it seems very helpful. However (using the docker container on Ubuntu 20.04) after install if you happen to turn off your server on restart EVERYTHING configured is gone. 
Would you have a proper step by step installation (the one provided on the page does NOT work if falls flat after the guacamole part) for Ubuntu 20 as explained above using the docker installation then the loss of data issue occurs
Thanks
Fuquan

**Comment by jimmy201602** [comment]
This project is still under development. Just give me some time to write a new guideline.
