### ISSUE TITLE
你好，有段代码不太明白。

### ISSUE THREAD

**Issue by kinzun** [jimmy201602/webterminal#195]
webterminal/consumers.py
from webterminal.interactive import SshTerminalThread, InterActiveShellThread
SshTerminalThread，InterActiveShellThread）

![image](https://user-images.githubusercontent.com/26301257/188116410-25859335-7fe9-4542-97ee-33795c07efa1.png)

这两个类，不太明白，都有转发消息功能， 关闭chan功能。 希望大佬解惑。

**Comment by jimmy201602** [comment]
放一个线程至后台，接收处理前端发来的信息！
