### ISSUE TITLE
Error: Value must be at most 40 characters when putting hostname

### ISSUE THREAD

**Issue by fWd82** [jimmy201602/webterminal#208]
Hi Dear,
My application is hosted on cloud and I am having just an IP. 
I am getting hostname from IP as: 
`> ping -a <IP>`
Which could not be the correct way, I don't know where to find hostname, because I did not bind domain name with my IP. 

If I am putting the hostname unfortunately the errors comes as "**Value must be at most 40 characters**" while mine is 49.

ecs-77-***-***-*66.reverse.open-telekom-cloud.com (49)

![Screenshot2](https://user-images.githubusercontent.com/19715150/221758038-5a026263-7459-4d3c-8839-8606b03a314a.PNG)

What should I do?
Can you may be please extend the limit up to 50 or something?

**Comment by jimmy201602** [comment]
not support.
