### ISSUE TITLE
modification

### ISSUE THREAD

**Issue by perfectwebtech** [jimmy201602/webterminal#216]
hello
what kind of modification i can do all is open source ? for participate as developer in this code ?

**Comment by jimmy201602** [comment]
You can contribute new functions to this project.

**Comment by jamaisx** [comment]
All but helper, or I am missing something?

**Comment by jimmy201602** [comment]
The source code of the helper is only for commercial users.

**Comment by jamaisx** [comment]
Good to know, has the product more functions? I see that in the opensource  there are unfinished functions. How to buy ?

**Comment by jimmy201602** [comment]
Please feel free to contact me by email at zhengge2012@gmail.com to get more details.
