### ISSUE TITLE
你的项目下午安装了下

### ISSUE THREAD

**Issue by Heart-Warming-Li** [jimmy201602/webterminal#23]
centos6.8  py2.7  安装过程出现好多问题（pysqlite问题，glibc2.14问题等），经过几个小时努力终于安装好。  运行起来进入项目，项目组不能创建，ssh也不能使用。提交就出现错误，可以说整个项目只能打开index页面。

请问接下来该如何操作。

**Comment by jimmy201602** [comment]
看到项目主页的QQ群号码了么!加群后找我QQ私聊
