### ISSUE TITLE
Make hosts password automatic

### ISSUE THREAD

**Issue by botti007** [jimmy201602/webterminal#24]
actually i need to stock all passwords's hosts into database then web terminal will get password from a database and connect to the server 
this will be more secure because users will never know host's password 
can i make dat ?? if it's possible please give me the name of the script that i can change into it to achieve this 
because i don't know the conception of you r project

**Comment by jimmy201602** [comment]
This project had already been achieved this! Please follow this document.
https://github.com/jimmy201602/webterminal/blob/master/doc/usage_en.md
