### ISSUE TITLE
Normal user gui and connection page

### ISSUE THREAD

**Issue by botti007** [jimmy201602/webterminal#28]
hello sir , i wanna ask 
did u add a normal user interface / login page  or not yet  ? 
i wanna know if this project also can be runned on mysql instead of sqlite if it be 
what i change and thank you so much

**Comment by jimmy201602** [comment]
The normal user login page had been replaced.

**Comment by botti007** [comment]
ok we are waiting for you for the next update 
cuz we have an mysql server and it will be more secure then db files espcially whene you stock server password instead of it
