### ISSUE TITLE
Always same probleme we can't capture vnc/rdp sessions

### ISSUE THREAD

**Issue by v3rlust** [jimmy201602/webterminal#29]
js 304 [0.02, 192.168.1.14:54009]
[2018/04/05 19:32:44] HTTP GET /static/img/user1.jpg 304 [0.03, 192.168.1.14:54019]
[2018/04/05 19:32:44] HTTP GET /static/fonts/toadOcfmlt9b38dHJxOBGEo0As1BFRXtCDhS66znb_k.woff2 304 [0.03, 192.168.1.14:54011]
[2018/04/05 19:32:44] HTTP GET /static/fonts/ODelI1aHBYDBqgeIAH2zlNV_2ngZ8dMf8fLgjYEouxg.woff2 304 [0.03, 192.168.1.14:54020]
[2018/04/05 19:32:46] HTTP GET /sshlogslist/ 200 [0.05, 192.168.1.14:54020]
[2018/04/05 19:32:48] HTTP GET /guacamole/logplay/1/ 200 [0.04, 192.168.1.14:54020]
[2018/04/05 19:32:48] HTTP GET /static/plugins/guacamole/all.min.js?_=1522956766230 200 [0.04, 192.168.1.14:54020]
[2018/04/05 19:32:48] HTTP GET /static/plugins/guacamole/playback.js?_=1522956766231 200 [0.05, 192.168.1.14:54020]
Not Found: /media/2018-4-5/88398d77-db56-4c86-9f10-86c9401f0a2c
[2018/04/05 19:32:48] HTTP GET /media/2018-4-5/88398d77-db56-4c86-9f10-86c9401f0a2c 404 [0.05, 192.168.1.14:54020]

please helpp we can't reaad rdp session log and vnc sessions
you said that you solve the capture rdp session after updating installation doc but always nothing happen when we try to replay the session we click on replay and nothing happen
however ssh works fine come on bro 
 you have an other problme with logout when you try to logout then log in in the same page of logout you can't log in you problem in url 
please help me to solve the first problem with vnc and rdp session
also an interface for normal user doesn't exist  we are waiting for the first time to fix rdp sessions reader and vnc session reader

**Comment by jimmy201602** [comment]
According to your description! It seems like the project haven’t capture any rdp or vnc session! Do you run guacamole server and webterminal seperate?
Can you connect to the remote rdp server or vnc server?Try to update the project to the latest version!
If the problem always persist!Try use my docker images ! Yesterday I just update it! It haven’t any problem!
The login page and the logout page are the same!
I haven’t finish it yet!

**Comment by jimmy201602** [comment]
I’m confused about your expect normal user interface? Would you like to draw some iamge or find a similar page to show me?

**Comment by jimmy201602** [comment]
```sh
[2018/04/05 19:32:48] HTTP GET /static/plugins/guacamole/playback.js?=1522956766231 200 [0.05, 192.168.1.14:54020]
Not Found: /media/2018-4-5/88398d77-db56-4c86-9f10-86c9401f0a2c
[2018/04/05 19:32:48] HTTP GET /media/2018-4-5/88398d77-db56-4c86-9f10-86c9401f0a2c 404 [0.05, 192.168.1.14:54020]
```
This log means the record hadn't created.
You can list the recording directory in the project named media.

For normal user you should configure view and log permission if you want user can view.

Try to update your project to the newest version and send me the settings.py.

**Comment by v3rlust** [comment]
actually i don't think so the problem is in settings.py because i said that i found capture files of SSH in /media directory 
so the probleme is in the rdp recorder anyway here is the settings.py : 
`# -*- coding: utf-8 -*-
"""
Django settings for webterminal project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$@naaul9f4zi*3s%bze)5cq)q5ufwi!gj5do=area84pimi9p*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webterminal',
    'channels',
    'rest_framework',
    'elfinder',
    'guacamole',
    'permission',
    'common',
    'guardian',
    'crispy_forms'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webterminal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n'
            ],
        },
    },
]

WSGI_APPLICATION = 'webterminal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Channels settings
CHANNEL_LAYERS = {
    "default": {
       "BACKEND": "asgi_redis.RedisChannelLayer",  # use redis backend
       "CONFIG": {
           "hosts": [("localhost", 6379)],  # set redis address
           "channel_capacity": {
                                   "http.request": 1000,
                                   "websocket.send*": 10000,
                                },
           "capacity": 10000,
           },
       "ROUTING": "webterminal.routing.channel_routing",  # load routing from our routing.py file
       },
}

#Rest framework api auth config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
    ),
}

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

LOCALE_PATHS = [
                os.path.join(BASE_DIR,'locale')
        ]


AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

CRISPY_TEMPLATE_PACK = 'bootstrap3'

from django.conf.locale.en import formats as en_formats
en_formats.DATETIME_FORMAT = 'Y-m-d H:i:s'
en_formats.DATETIME_INPUT_FORMATS = 'Y-m-d H:i:s'

LANGUAGES = [
    ('zh-hans', _('Simple Chinese')),
    ('en', _('English')),
]

CHANNELS_WS_PROTOCOLS = ["guacamole"]

# guacd daemon host address and port
GUACD_HOST = '127.0.0.1'
GUACD_PORT = '4822'`

**Comment by jimmy201602** [comment]
There is any difference to my project settings. Try use docker to run the project.
Maybe is the environment problem.
```sh
docker pull webterminal/webterminal
docker run -itd -p 80:80 webterminal/webterminal
Login user & password
username: admin
password: password!23456
```

**Comment by v3rlust** [comment]
actually we use VMs to install you r project and i don t think so it s a problem of environnement because SSH recorder works fine and for Docker containers  my boss has refuse that for some reasons 
anyway to contact me i send you email "mohamedali.belhajali@gmail.com"
or you can tell me which IM tools you are always connected on and give me you ID i will contact you please we are waiting for you

**Comment by jimmy201602** [comment]
User auth bug and several  other bug.

**Comment by v3rlust** [comment]
I hope you fixed Rdp and VNC recorder we will update you r project and try it again and i'll give you our feedback thank you so much 
i hope it works fine

**Comment by v3rlust** [comment]
always same problem with RDP/vnc connect fine but no record  
SSH works fine and also the ssh recorder works fine 
Ssh session not found in /media please try you'r project in VM it was a problem of using this project in VM's

**Comment by jimmy201602** [comment]
Just send you a email. If you see it. Download the app and add me. I can help you run this project and solve problem more efficient.

**Comment by v3rlust** [comment]
I actually did that i'am wainting you to responds
