### ISSUE TITLE
telnet 交换机测试报错不可使用

### ISSUE THREAD

**Issue by TelDragon** [jimmy201602/webterminal#32]
环境 
Centos7
python 2.7.5
pip 9.0.3

前台web 不显示

附上服务器log错误信息
![factlogo](https://github.com/TelDragon/Dragon/blob/master/QQ%E5%9B%BE%E7%89%8720180411100045.png?raw=true)

**Comment by jimmy201602** [comment]
telnet协议暂时未测试完

**Comment by jimmy201602** [comment]
已完成telnet协议，telnet协议现已可用

**Comment by jimmy201602** [comment]
已完成telnet协议，telnet协议现已可用
