### ISSUE TITLE
Asking Questions

### ISSUE THREAD

**Issue by botti007** [jimmy201602/webterminal#35]
Hi , 
i just wanna ask if you can add Calendar restriction and "Commands restriction" and solve the probleme of logout 
"calendar restriction" means that there is some users that are not authorised to use webterminal in a periode of Time or in some days 
"Commands restriction" can you add it in SSH/telnet Connexion that we can limit commands like if users use Sudo ..... the cannection will be cut off 

i hope you add this in somedays and thank you

**Comment by jimmy201602** [comment]
In the future! I will consider these staff. For now I haven't enough time to finish that.
