### ISSUE TITLE
ssh终端页面过长，导致滚动条不可控的问题

### ISSUE THREAD

**Issue by kevindwei** [jimmy201602/webterminal#36]
把templates/webterminal/index.html里面的make_terminal(document.getElementById(tabId), {rows: 40, cols: 90}, ws_path, ip);  rows行数改少有点就可以了 表示页面固定显示的行数，建议行数修改为28

**Comment by jimmy201602** [comment]
后续优化

**Comment by jimmy201602** [comment]
UI优化问题后续进行
