### ISSUE TITLE
docker容器启动成功，但地址无法访问

### ISSUE THREAD

**Issue by xujj2017** [jimmy201602/webterminal#39]
![1](https://user-images.githubusercontent.com/30644400/39228549-4b733f98-4891-11e8-9d19-674d07282005.jpg)

容器启动ok了，但地址无法访问。
主机系统为centos7，防火墙已经关闭了。

**Comment by jimmy201602** [comment]
请尝试直接访问docker容器ip:80，看是否可以访问
