### ISSUE TITLE
不管在哪个主机上点右键选择“file_manager”连接的都是同一台主机？？

### ISSUE THREAD

**Issue by fjibj** [jimmy201602/webterminal#5]
一旦某台主机file-manager成功后，后续无论在“server list"中选择哪台主机右击“file_manager"打开的还是这台主机，而不是选中的主机

**Comment by jimmy201602** [comment]
这个有待考证哦！

**Comment by jimmy201602** [comment]
建议用最新版本试试

**Comment by fjibj** [comment]
用了最新版本也不行，我觉得问题在于elfinder的缓存上，我在elfinder上也提了issue,目前问题尚未解决。
