### ISSUE TITLE
color vim

### ISSUE THREAD

**Issue by py2010** [jimmy201602/webterminal#50]
今天因SFTP文件上传下载看到当前项目，想起去年就是借鉴贵项目的web终端，当时发现不能彩色vim的问题。
webterminal/webterminal/consumers.py
105                      chan = self.ssh.invoke_shell(width=width, height=height,)
============>
                            chan = self.ssh.invoke_shell(term='xterm', width=width, height=height,)

默认是哑终端，设置终端为xterm、vt100等可使vi为彩色。

**Comment by jimmy201602** [comment]
感谢提意见，后续这块会调整下
