### ISSUE TITLE
nginx抱502 bad gateway错误

### ISSUE THREAD

**Issue by uncarman2017** [jimmy201602/webterminal#51]
检查日志，发现
2018/06/03 13:54:16 [crit] 7784#0: *1 connect() to 0.0.0.0:8000 failed (13: Permission denied) while connecting to upstream, client: 10.17.4.128, server: localhost, request: "GET / HTTP/1.1", upstream: "http://0.0.0.0:8000/", host: "172.16.22.110"

**Comment by jimmy201602** [comment]
请更新最新的docker镜像试下
