### ISSUE TITLE
请问，docker部署的话，直接按README里面的docker部分命令就可以吗？我试了一下，不ok

### ISSUE THREAD

**Issue by lijinghuatongxue** [jimmy201602/webterminal#52]

**Comment by jimmy201602** [comment]
首先你要安装docker，然后拉取docker镜像，最后按照要求启动docker镜像即可

**Comment by lijinghuatongxue** [comment]
#我使用的阿里云加速，已经下载完镜像，也按照readme里面的重启了，浏览器输入的是 http://外网ip:80,没有任何反应。我想知道启动了该镜像之后还需要进行什么操作吗

docker pull registry.cn-hangzhou.aliyuncs.com/webterminal/webterminal
docker run -itd -p 80:80 webterminal/webterminal

**Comment by jimmy201602** [comment]
http://外网ip:80 外网ip指的是你实际的ip地址，如果是阿里云服务器的话，你得看下是不是80端口默认关闭了，或者说被安全策略限制了 你可以加下webterminal讨论QQ群（531612760），让大家帮你看看到底是那块出问题了
