### ISSUE TITLE
centos7 编译安装无G盘

### ISSUE THREAD

**Issue by TaveMyliuX** [jimmy201602/webterminal#54]
文件上传五G盘，日志出现：
guacd[13088]: Failed to load guacdr plugin. Drive redirection and printing will not work. Sound MAY not work.
guacd[13088]: Failed to load guacsnd alongside guacdr plugin. Sound will not work. Drive redirection and printing MAY not work.

这个问题是freerdp的库默认安装在/usr/local/lib/freerdp下了，copy到centos默认的路径就行。
cp /usr/local/lib/freerdp/* /usr/lib64/freerdp/

**Comment by jimmy201602** [comment]
已合并至文档
