### ISSUE TITLE
GuacamoleWebsocket 在python3运行问题

### ISSUE THREAD

**Issue by pythonzm** [jimmy201602/webterminal#57]
大佬，我把你的有关Guacamole的后端代码用最新的django-channel，改了一下，前端代码没弄，但是每次连接都会提示如下：
WebSocket connection to 'ws://10.1.19.10:8000/guacamole/?undefined' failed: Error during WebSocket handshake: Unexpected response code: 500

我不太明白传的参数为什么是undefined，需要修改js的代码么？

**Comment by jimmy201602** [comment]
服务端报错了,请将详细日志附上
