### ISSUE TITLE
docker 启动容器后里面的时间不是北京东8区时间

### ISSUE THREAD

**Issue by 156889031** [jimmy201602/webterminal#58]
[root@centos ~]# date -R
Wed, 16 Jan 2019 23:07:14 +0800
[root@centos ~]# 

root@b612398d624d:/etc# date -R
Wed, 16 Jan 2019 15:07:37 +0000
root@b612398d624d:/etc#

**Comment by jimmy201602** [comment]
时间这块docker里面没注意，不过默认项目是用的utc时间
![image](https://user-images.githubusercontent.com/17548183/51377118-0873a200-1b45-11e9-8de2-cc2448d5a316.png)

**Comment by 156889031** [comment]
如何修改成，北京时间呢？
谢谢！

**Comment by 156889031** [comment]
可以提供一个修改配置的文档或是直接操作的方法，由我们使用者，自己更改也可以！谢谢！

**Comment by 156889031** [comment]
请告知修改北京时间的方法，
谢谢！、


wtgmail@163.com
 
发件人： jimmy201602
发送时间： 2019-01-19 17:06
收件人： jimmy201602/webterminal
抄送： 156889031; Author
主题： Re: [jimmy201602/webterminal] docker 启动容器后里面的时间不是北京东8区时间 (#58)
Closed #58.

**Comment by 156889031** [comment]
刚才的文件，在哪个目录，UTC 修改成Asia/Shanghai就可以 ？


wtgmail@163.com
 
发件人： wtgmail@163.com
发送时间： 2019-02-05 15:20
收件人： jimmy201602/webterminal
主题： Re: Re: [jimmy201602/webterminal] docker 启动容器后里面的时间不是北京东8区时间 (#58)

请告知修改北京时间的方法，
谢谢！、


wtgmail@163.com
 
发件人： jimmy201602
发送时间： 2019-01-19 17:06
收件人： jimmy201602/webterminal
抄送： 156889031; Author
主题： Re: [jimmy201602/webterminal] docker 启动容器后里面的时间不是北京东8区时间 (#58)
Closed #58.
