### ISSUE TITLE
js bug

### ISSUE THREAD

**Issue by ynhao** [jimmy201602/webterminal#6]
在你的代码/templates/webterminal/credentialcreate.html中，有这么一行代码schemas["$.password"] = schema;将导致无论是添加的密钥登录还是密码登录都将会以password字段传给后台程序，导致在添加密钥登录时会报错

**Comment by jimmy201602** [comment]
谢谢你的反馈，我将尽快修复此bug。

**Comment by jimmy201602** [comment]
The bug has been fixed!
