### ISSUE TITLE
请告知一下docker里面修改成北京时间的方法，最好能有具体的方法文档

### ISSUE THREAD

**Issue by 156889031** [jimmy201602/webterminal#69]

**Comment by jimmy201602** [comment]
后续更改

**Comment by 156889031** [comment]
很期待哦！

**Comment by jimmy201602** [comment]
此问题不涉及webterminal项目本身,使用Linux的常见问题之一.具体设置你可以参考这篇文章去设置https://www.cnblogs.com/highend/p/docker_container_china_timezone.html
