### ISSUE TITLE
权限管理说明建议

### ISSUE THREAD

**Issue by 156889031** [jimmy201602/webterminal#70]
权限列表里面有很多权限，可以根据用户自己的需求，自定义，很灵活，要是有粗略的需求，如审计员、运维员，管理员等权限的时候，得自己找对应的，建议：出厂有这三个管理员就好了，同时保留原有的灵活性。

**Comment by jimmy201602** [comment]
权限控制将在1.0版本之后考虑

**Comment by jimmy201602** [comment]
此功能将在1.0版本之后优化细分,暂时无太多精力处理
