### ISSUE TITLE
项目的安装问题

### ISSUE THREAD

**Issue by 156889031** [jimmy201602/webterminal#71]
使用docker安装，每次更新完毕后，配置都不在了，很是不方便，使用命令安装，往往有些复杂，安装不上，建议，是否可以做一个脚本文件，来一键安装，安装完毕后，下次开启，自动启动相关服务。这样更方便使用和推广。
谢谢！项目创始人！

**Comment by jimmy201602** [comment]
尽快更改说明文档

**Comment by 156889031** [comment]
很是期待哦！

**Comment by jimmy201602** [comment]
docker安装后程序更新配置不在问题,请参考以下步骤进行更新操作(建议你去学习下docker相关知识):
1:以root权限用户执行命令 docker ps -a 执行结果示例如下
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                     PORTS                                                    NAMES
74353eddb77a        3fd398450291               "/bin/bash"              2 days ago          Exited (127) 2 days ago                                                             nostalgic_cartwright
记录所需要更新的docker container id 如74353eddb77a
2:以root权限账户执行 docker exec -it 74353eddb77a /bin/bash 进入docker容器内部
3:cd /opt/webterminal进入项目源代码目录执行如下命令更新代码
git pull
4:重启容器中webterminal服务使更新的代码生效,命令如下
supervisorctl restart all
5:exit退出容器即可
