### ISSUE TITLE
每點擊新頁面彈出 ssh 連結

### ISSUE THREAD

**Issue by enzokwai** [jimmy201602/webterminal#90]
每點擊新頁面彈出 ssh 連結，chrome 提示 要開啓『WINSCP:SFTP...and SCP Client 』嗎？如果選擇開啓會打開一putty 連結到 "test" . "test" 不存在所以putty 沒有反應。

在 chrome 的 developer tool 追蹤到

openUriWithTimeoutHack | @ | protocolcheck.js:74
-- | -- | --
  | module.exports | @ | protocolcheck.js:195
  | (anonymous) | @ | (index):501
  | i | @ | jquery-2.2.3.min.js:2
  | fireWith | @ | jquery-2.2.3.min.js:2
  | ready | @ | jquery-2.2.3.min.js:2
  | J | @ | jquery-2.2.3.min.js:2

rdp 和 ssh 連線功能能正常使用的，

**Comment by jimmy201602** [comment]
这个不是bug，是为了测试客户端是否安装了ssh调用助手用的。由于现在调用助手还没有完全完成功能导致。请关注此项目，后续更新ssh调用助手后即可。

**Comment by jimmy201602** [comment]
已更新ssh调用助手

**Comment by jimmy201602** [comment]
已修复,windows 7/8/10测试均通过
